version: '3.4'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
  Lumbre.WebAPI:
    image: ${DOCKER_REGISTRY-}lumbre.webapi
    build:
      context: .
      dockerfile: Lumbre.WebAPI/Dockerfile
volumes:
   mongodb_data_container:

