version: '3.4'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro

  samplehost:
    image: ${DOCKER_REGISTRY-}samplehost
    ports:
      - 5000:5000
      - 8080:8080
    build:
      context: .
      dockerfile: SampleHost/Dockerfile


volumes:
   mongodb_data_container:


